server:
  port: 5158
spring:
  application:
    name: microservice-customer-turbine
  zipkin:
    baseUrl: http://localhost:11811
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      turbine-cluster-key: TYSJKF
feign:
  hystrix:
    enabled: true
#聚合地址：http://localhost:5158/turbine.stream?cluster=TYSJKF
turbine:
  aggregator:
    clusterConfig: TYSJKF # 指定聚合哪些集群，多个使用","分割。
  appConfig: MICROSERVICE-CUSTOMER-TURBINE,MICROSERVICE-CUSTOMER-USER # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: metadata['turbine-cluster-key'] #指定eureka中定义的集群的key（turbine-cluster-key）对应的值，即集群的名字