server:
  port: 8080
spring:
  application:
    name: microservice-provider-oauth2
  zipkin:
    baseUrl: http://localhost:11811
  redis:
      host: localhost
      port: 6379
      #password:
      database: 1
      timeout: 0
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 500
         min-idle: 0
    #  sentinel:   #开启哨兵模式
    #     master: redis-master # name of Redis server
     #    nodes:  127.0.0.1:1001,127.0.0.1:1002# comma-separated list of host:port pairs
  datasource:
     url: jdbc:mysql://localhost:3306/oauth2
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
       turbine-cluster-key: TYSJKF
feign:
  hystrix:
    enabled: true